[package]
name = "my-jira"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.83"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
